version: '3'
services:
  # python:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   container_name: 'assistant'
  #   working_dir: '/assistant'
  #   tty: true
  #   volumes:
  #     - ./:/assistant
  server:
    restart: always
    build:
      context: .
      dockerfile: ./server.Dockerfile
    container_name: 'assistantServer'
    working_dir: '/assistant'
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/assistant
